export const SET_NO_OF_TRIES = 'SET_NO_OF_TRIES';
export const SET_QUIZZES = 'SET_QUIZZES'
export const SET_CURRENT_QUIZ = 'SET_CURRENT_QUIZ'
export const RESET_FOR_NEW_TEST = 'RESET_FOR_NEW_TEST'


export const SET_CURRENT_RIGHT_ANSWER = 'SET_CURRENT_RIGHT_ANSWER'
export const SET_ANSWERED = 'SET_ANSWERED'
export const SET_IS_ANSWER_CORRECT = 'SET_IS_ANSWER_CORRECT'
export const SET_CORRECT_ANSWER_COUNT = 'SET_CORRECT_ANSWER_COUNT'

export const SET_CURRENT_QUESTIONS_SET = 'SET_CURRENT_QUESTIONS_SET'
